/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{js,ts,tsx}', './components/**/*.{js,ts,tsx}'],

  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#f8f9fb',
        'on-background': '#191c1e',
        surface: '#f8f9fb',
        'surface-dim': '#d9dadc',
        'surface-bright': '#f8f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f6',
        'surface-container': '#edeef0',
        'surface-container-high': '#e7e8ea',
        'surface-container-highest': '#e1e2e4',
        'on-surface': '#191c1e',
        'on-surface-variant': '#434654',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f3',
        outline: '#737685',
        'outline-variant': '#c3c6d6',
        'surface-tint': '#0c56d0',
        primary: '#003d9b',
        'on-primary': '#ffffff',
        'primary-container': '#0052cc',
        'on-primary-container': '#c4d2ff',
        'inverse-primary': '#b2c5ff',
        secondary: '#535f73',
        'on-secondary': '#ffffff',
        'secondary-container': '#d4e0f8',
        'on-secondary-container': '#576377',
        tertiary: '#7b2600',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a33500',
        'on-tertiary-container': '#ffc6b2',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b2c5ff',
        'on-primary-fixed': '#001848',
        'on-primary-fixed-variant': '#0040a2',
        'secondary-fixed': '#d7e3fb',
        'secondary-fixed-dim': '#bbc7de',
        'on-secondary-fixed': '#101c2d',
        'on-secondary-fixed-variant': '#3b475b',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#ffb59b',
        'on-tertiary-fixed': '#380d00',
        'on-tertiary-fixed-variant': '#812800',
        'surface-variant': '#e1e2e4',
        dark: {
          background: '#101419',
          'on-background': '#e0e2ea',
          surface: '#101419',
          'surface-dim': '#101419',
          'surface-bright': '#363940',
          'surface-container-lowest': '#0b0e14',
          'surface-container-low': '#181c22',
          'surface-container': '#1c2026',
          'surface-container-high': '#262a30',
          'surface-container-highest': '#31353b',
          'on-surface': '#e0e2ea',
          'on-surface-variant': '#c0c7d4',
          'inverse-surface': '#e0e2ea',
          'inverse-on-surface': '#2d3137',
          outline: '#8a919d',
          'outline-variant': '#404752',
          'surface-tint': '#a2c9ff',
          primary: '#a2c9ff',
          'on-primary': '#00315b',
          'primary-container': '#47a1ff',
          'on-primary-container': '#003663',
          'inverse-primary': '#0060a9',
          secondary: '#b9c8de',
          'on-secondary': '#233143',
          'secondary-container': '#39485a',
          'on-secondary-container': '#a7b6cc',
          tertiary: '#ffb868',
          'on-tertiary': '#482900',
          'tertiary-container': '#e08a00',
          'on-tertiary-container': '#4f2d00',
          error: '#ffb4ab',
          'on-error': '#690005',
          'error-container': '#93000a',
          'on-error-container': '#ffdad6',
          'primary-fixed': '#d3e4ff',
          'primary-fixed-dim': '#a2c9ff',
          'on-primary-fixed': '#001c38',
          'on-primary-fixed-variant': '#004881',
          'secondary-fixed': '#d4e4fa',
          'secondary-fixed-dim': '#b9c8de',
          'on-secondary-fixed': '#0d1c2d',
          'on-secondary-fixed-variant': '#39485a',
          'tertiary-fixed': '#ffddbb',
          'tertiary-fixed-dim': '#ffb868',
          'on-tertiary-fixed': '#2b1700',
          'on-tertiary-fixed-variant': '#673d00',
          'surface-variant': '#31353b',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        18: '4.5rem',
      },
    },
  },
  plugins: [],
};
